### PR TITLE
Add TypeScript support

### PR DESCRIPTION
**Pull request by bbabou**

### CODE REVIEW

**Comment by ryzyx** [comment]
Why ts support though, can't u use just the javascript package. I am not familiar with TS a lot as of yet, I'd need someone to review it or i need to opt for an alternate method

**Comment by bbabou** [comment]
TypeScript is better for safety, I let you know more about it, it's better for the future of this project.
Sorry for my bad english, I'm french ;)

**Comment by ryzyx** [comment]
Once i get someone to review this PR and test it and make sure there is no problem. This will be merged. As of now I am closing this PR.

**Comment by kernelwernel** [comment]
@ryzyx I scrolled through and tested the PR, it works as intended. Also, you shouldn't limit your own package user audience to only javascript users. It's far better to add support for typescript when it has many features that javascript doesn't have.

**Comment by ryzyx** [comment]
Man sure, I'd love to add Typescript support but I do not know Typescript well enough yet. Also I'll need to update 3 versions which are msg, interactions and ts. It'll become complicated for users. Whenever there'll be some changes in the TS version. I wont be able to do it. I can rely on someone to hopefully create a PR and fix it. Hope u understand

**Pull request closed without merging**
